- name: set JAVA_HOME environment variable
  lineinfile: path=/home/ubuntu/.profile line='export JAVA_HOME=/usr/lib/jvm/java-8-oracle' insertafter=EOF

- name: set JAVA PATH environment variable
  lineinfile: path=/home/ubuntu/.profile line='export PATH=$PATH:$JAVA_HOME' insertafter=EOF
